@echo off
echo Building...
make
echo Stripping...
arm-none-eabi-strip 3DS-Controller.elf
echo Converting...
makerom -f cci -o controller.3ds -rsf "cxi/gw_workaround.rsf" -target d -exefslogo -elf 3DS-Controller.elf -icon "cxi/icon.icn" -banner "cxi/banner.bnr"
echo Done!